### PR TITLE
fix: npm install with npm 7

### LINKED ISSUE #541: vaadin-router doesn't run in npm7 (node 15)
To reproduce:
1. Install npm 7
2. in the vaadin-router root directory, run `npm install`
3. See the error messages
```
vaadin-router % npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! Found: eslint@7.18.0
npm ERR! node_modules/eslint
npm ERR!   dev eslint@"^7.15.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! dev eslint-config-vaadin@"0.2.7" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: eslint@5.16.0
npm ERR! node_modules/eslint
npm ERR!   peer eslint@"^5.0.0" from eslint-config-vaadin@0.2.7
npm ERR!   node_modules/eslint-config-vaadin
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/haijian/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/haijian/.npm/_logs/2021-01-29T10_26_31_733Z-debug.log
```

### PR DESCRIPTION
**Pull request by Haprog**
npm install was failing with npm 7 unless using the `--legacy-peer-deps`
flag. Remove dependency to old version of `eslint-config-vaadin`
and `stylelint-config-vaadin` while adapting the configs to try to keep
the rules mostly the same for now. We might consider using the latest
version of `eslint-config-vaadin` and `stylelint-config-vaadin` again when
we migrate away from bower and HTML Imports and maybe migrate
this repo to use TypeScript.

The problem was old versions of `eslint` and `stylelint` declared as peer dependencies of `eslint-config-vaadin` and `stylelint-config-vaadin` and we can't yet use newer versions of `eslint-config-vaadin` and `stylelint-config-vaadin` because they have changed to support LitElement and TypeScript based projects and those configs don't work as is for vaadin-router which is still based on HTML Imports and doesn't use TS.

Fixes #541.

### CODE REVIEW

File: src/resolver/resolver.js [hunk 1]
```diff
@@ -222,7 +222,7 @@ class Resolver {
       ? this.constructor.__createUrl(
         this.baseUrl,
         document.baseURI || document.URL
-      ).href.replace(/[^\/]*$/, '')
```
Comment (Haprog) [inline src/resolver/resolver.js:225]: This was an unnecessary escape (complained by linter rule). Most characters don't need to be escaped inside a character group `[]`.

File: src/router.js [hunk 2]
```diff
@@ -172,7 +172,7 @@ export class Router extends Resolver {
     const baseHref = baseElement && baseElement.getAttribute('href');
     super([], Object.assign({
       // Default options
-      baseUrl: baseHref && Resolver.__createUrl(baseHref, document.URL).href.replace(/[^\/]*$/, '')
```
Comment (Haprog) [inline src/router.js:175]: This was an unnecessary escape (complained by linter rule). Most characters don't need to be escaped inside a character group `[]`.

**Review by haijian-vaadin — APPROVED** [review]
Tried locally with npm7, works for me
